# Generated by Django 6.0.3 on 2026-07-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("created_date",)},
        ),
    ]
