# Generated by Django 6.0.3 on 2026-07-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_counted_view_post_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
    ]
