# Generated by Django 6.0.3 on 2026-08-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="approach",
            new_name="approved",
        ),
    ]
