# Generated by Django 6.0.3 on 2026-08-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_approach_comment_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
    ]
