# Generated by Django 6.0.3 on 2026-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="login_required",
            field=models.BooleanField(default=False),
        ),
    ]
