# Generated by Django 6.0.3 on 2026-08-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_post_login_required"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="login_required",
            new_name="login_require",
        ),
    ]
